# .goreleaser.yml

# Only create a GitHub release and tag; no binaries
release:
  github:
    owner: grasp-labs
    name: ds-go-echo-middleware
  draft: false
  prerelease: false

builds: 
  - skip: true # building a library, should not build.

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

# Skip artifacts, but still generate release with tags and changelog
archives: []
